apiVersion: v1
kind: Service
metadata:
  name: {{ include "case-poc.fullname" . }}-submission
  labels:
    {{- include "case-poc.labels" . | nindent 4 }}
    app.kubernetes.io/name: submission-service
spec:
  type: ClusterIP
  selector:
    {{- include "case-poc.selectorLabels" (dict "root" . "component" "submission-service") | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "case-poc.fullname" . }}-management
  labels:
    {{- include "case-poc.labels" . | nindent 4 }}
    app.kubernetes.io/name: management-service
spec:
  type: ClusterIP
  selector:
    {{- include "case-poc.selectorLabels" (dict "root" . "component" "management-service") | nindent 4 }}
  ports:
    - name: http
      port: 8081
      targetPort: http
