apiVersion: v1
kind: Secret
metadata:
  name: {{ include "case-poc.fullname" . }}-artemis-auth
  labels:
    {{- include "case-poc.labels" . | nindent 4 }}
type: Opaque
stringData:
  ARTEMIS_USER: {{ .Values.artemis.user | quote }}
  ARTEMIS_PASSWORD: {{ .Values.artemis.password | quote }}
