apiVersion: v1
kind: Service
metadata:
  name: {{ include "case-poc.fullname" . }}-keycloak
  labels:
    {{- include "case-poc.labels" . | nindent 4 }}
    app.kubernetes.io/name: keycloak
spec:
  type: ClusterIP
  selector:
    {{- include "case-poc.selectorLabels" (dict "root" . "component" "keycloak") | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
