#!/usr/bin/env bash
#
# Creates (or reuses) the multipass VM for the k8s POC, mounts the repo at
# /repo inside the VM, and provisions the CIS-hardened k3s server with
# Ansible run FROM THE HOST (the controller) over SSH:
#
#   host (controller: multipass, ansible, ssh keypair)
#     └── ssh -> VM "case-poc"  (provisioned by deploy/vm/ansible/k3s-playbook.yml)
#
#   bash scripts/vm-up.sh
#
# Idempotent: re-running re-applies the playbook (refreshes config, restarts
# k3s if needed) and re-exports the kubeconfig. On Windows, mounts must be
# enabled once beforehand: multipass set local.privileged-mounts=true
set -euo pipefail

VM_NAME="${VM_NAME:-case-poc}"
VM_CPUS="${VM_CPUS:-4}"
VM_MEMORY="${VM_MEMORY:-8G}"
VM_DISK="${VM_DISK:-40G}"
UBUNTU_IMAGE="${UBUNTU_IMAGE:-24.04}"
SSH_KEY="${SSH_KEY:-$HOME/.ssh/multipass-$VM_NAME}"

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ANSIBLE_DIR="$REPO_DIR/deploy/vm/ansible"

command -v multipass >/dev/null || { echo "multipass not found (https://canonical.com/multipass)"; exit 1; }
command -v ansible-playbook >/dev/null || { echo "ansible-playbook not found (macOS: brew install ansible)"; exit 1; }

# Git Bash rewrites arguments that look like POSIX paths before they reach the
# native multipass.exe; VM-side paths (/repo/...) must stay untouched, while
# host-side paths must be converted explicitly (host_path).
mp() { MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*' multipass "$@"; }
host_path() { if command -v cygpath >/dev/null 2>&1; then cygpath -m "$1"; else printf '%s' "$1"; fi; }

if [ ! -f "$SSH_KEY" ]; then
  echo "==> Generating controller SSH keypair $SSH_KEY"
  ssh-keygen -t ed25519 -N '' -C "ansible-controller-$VM_NAME" -f "$SSH_KEY" >/dev/null
fi

if ! mp info "$VM_NAME" >/dev/null 2>&1; then
  echo "==> Launching multipass VM '$VM_NAME' (Ubuntu $UBUNTU_IMAGE, $VM_CPUS CPUs, $VM_MEMORY RAM, $VM_DISK disk)"
  mp launch "$UBUNTU_IMAGE" --name "$VM_NAME" \
    --cpus "$VM_CPUS" --memory "$VM_MEMORY" --disk "$VM_DISK" \
    --timeout 900
else
  echo "==> VM '$VM_NAME' already exists; reusing"
  mp start "$VM_NAME"
fi

# Key injection via exec instead of cloud-init: it also covers VMs that
# already exist (cloud-init only runs on first boot).
echo "==> Authorizing the controller key for user ubuntu"
mp exec "$VM_NAME" -- bash -c "grep -qF '$(cat "$SSH_KEY.pub")' ~/.ssh/authorized_keys 2>/dev/null \
  || echo '$(cat "$SSH_KEY.pub")' >> ~/.ssh/authorized_keys"

if ! mp info "$VM_NAME" --format json | grep -q '"/repo"'; then
  echo "==> Mounting repo at $VM_NAME:/repo"
  mp mount "$(host_path "$REPO_DIR")" "$VM_NAME:/repo"
fi

VM_IP="$(mp exec "$VM_NAME" -- hostname -I | tr -d '\r' | awk '{print $1}')"

echo "==> Writing inventory ($VM_NAME @ $VM_IP)"
cat > "$ANSIBLE_DIR/inventory.ini" <<EOF
# Generated by scripts/vm-up.sh - do not edit (gitignored)
[case_poc]
$VM_IP ansible_user=ubuntu ansible_ssh_private_key_file=$SSH_KEY
EOF

echo "==> Provisioning hardened k3s (ansible-playbook from the host)"
ANSIBLE_CONFIG="$ANSIBLE_DIR/ansible.cfg" ansible-playbook \
  -i "$ANSIBLE_DIR/inventory.ini" "$ANSIBLE_DIR/k3s-playbook.yml"

echo "==> Exporting kubeconfig for host kubectl -> .vm-kubeconfig.yaml (gitignored)"
mp exec "$VM_NAME" -- sudo cat /etc/rancher/k3s/k3s.yaml \
  | sed "s/127\\.0\\.0\\.1/$VM_IP/" > "$REPO_DIR/.vm-kubeconfig.yaml"
chmod 600 "$REPO_DIR/.vm-kubeconfig.yaml"

echo
echo "==> Done."
echo "VM IP:    $VM_IP  (Traefik ingress on port 80)"
echo "kubectl:  kubectl --kubeconfig .vm-kubeconfig.yaml get pods -A"
echo "Shell:    multipass shell $VM_NAME"
